# Global configuration settings
proj_name: test_project
threads: 64

# 01_exon_assembly_and_extraction configuration
read1: reads_1.fastq
read2: reads_2.fastq
mega353: angiosperms353_v2_interim_targetfile.fasta
gene_list: gene_list.txt
overlap: 0.8
output_hyb: 01_hyb_output
output_exon: 02_exon_extracted

# 02_phylo_results configuration
input_exon: 02_exon_extracted
ref_alignment: ref
gene_list: gene_list.txt
output_phylo: 03_phylo_results
min_exon_size: 80
tree_method: fasttree         # "fasttree"or "iqtree"
iqtree_mode: fixed            # if choose iqtree, options: fixed, fixed+gamma, mfp

# 03_cumulative_distance configuration
input_phylo: 03_phylo_results
output_tree: 04_all_trees
threshold: 1.96
use_flag: false               # true or false
use_threshold: true           # true or false (should not both be true with use_flag)

# Prediction/summary
input_file: 04_all_trees/test_project.cumulative_dist.csv
output_file: 04_all_trees/test_project.summary_scores.csv
taxonomic_level: o            # o = Order, f = Family, g = Genus, s = Species
zscore_threshold: 1.0
taxonomy_output_file: selected_taxa.txt